<a href="https://colab.research.google.com/github/Aswin-Kumar66/ml-practise/blob/main/kaggle_spaceship_titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from google.colab import files
import io

uploaded = files.upload()
uploaded1 = files.upload()

Saving train (1).csv to train (1).csv

Saving test (1).csv to test (1).csv

In [81]:
train = pd.read_csv(io.BytesIO(uploaded['train (1).csv']))
test = pd.read_csv(io.BytesIO(uploaded1['test (1).csv']))

In [6]:
train.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

In [10]:
train.shape

(8693, 14)

In [12]:
train.isna().sum()

PassengerId       0
HomePlanet      201
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name            200
Transported       0
dtype: int64

In [58]:
train = train.drop('Cabin' , axis = 1)
train = train.drop('PassengerId' , axis = 1)
train = train.drop('Name' , axis = 1)
train.head()

,HomePlanet,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported
0,Europa,False,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,False
1,Earth,False,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,True
2,Europa,False,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,False
3,Europa,False,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,False
4,Earth,False,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,True

In [31]:
train.dtypes

HomePlanet       object
CryoSleep        object
Destination      object
Age             float64
VIP              object
RoomService     float64
FoodCourt       float64
ShoppingMall    float64
Spa             float64
VRDeck          float64
Transported        bool
dtype: object

In [39]:
# train['CryoSleep'] = train['CryoSleep'].astype('string')
# train['HomePlanet'] = train['HomePlanet'].astype('string')
# train['Destination'] = train['Destination'].astype('string')
# train['VIP'] = train['VIP'].astype('string')

# train.head()

,HomePlanet,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported
0,Europa,False,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,False
1,Earth,False,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,True
2,Europa,False,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,False
3,Europa,False,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,False
4,Earth,False,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,True

In [59]:
train['HomePlanet'].fillna('OtherPlanet' , inplace = True)
train['Destination'].fillna('OtherDestination' , inplace = True)
train['CryoSleep'].fillna(False , inplace = True)
train['VIP'].fillna(False , inplace = True)

lst = [ 'Age' , 'RoomService' , 'FoodCourt' , 'ShoppingMall' , 'Spa' , 'VRDeck']

for l in lst :
  train[l].fillna(train[l].mean() , inplace = True)

train.isna().sum()

HomePlanet      0
CryoSleep       0
Destination     0
Age             0
VIP             0
RoomService     0
FoodCourt       0
ShoppingMall    0
Spa             0
VRDeck          0
Transported     0
dtype: int64

In [52]:
train['CryoSleep'].mode()

0    False
Name: CryoSleep, dtype: object

In [60]:
from sklearn.preprocessing import LabelEncoder

label_encoder =  LabelEncoder()

train['HomePlanet'] = label_encoder.fit_transform(train['HomePlanet'])
train['Destination'] = label_encoder.fit_transform(train['Destination'])
# train['Cryosleep'] = label_encoder.fit_transform(train['Cryosleep'])
# train['VIP'] = label_encoder.fit_transform(train['VIP'])
train['Transported'] = label_encoder.fit_transform(train['Transported'])

train.head()

,HomePlanet,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported
0,1,False,3,39.0,False,0.0,0.0,0.0,0.0,0.0,0
1,0,False,3,24.0,False,109.0,9.0,25.0,549.0,44.0,1
2,1,False,3,58.0,True,43.0,3576.0,0.0,6715.0,49.0,0
3,1,False,3,33.0,False,0.0,1283.0,371.0,3329.0,193.0,0
4,0,False,3,16.0,False,303.0,70.0,151.0,565.0,2.0,1

In [62]:
train['CryoSleep'] = label_encoder.fit_transform(train['CryoSleep'])
train['VIP'] = label_encoder.fit_transform(train['VIP'])

train.head()

In [64]:
train.head()

,HomePlanet,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported
0,1,0,3,39.0,0,0.0,0.0,0.0,0.0,0.0,0
1,0,0,3,24.0,0,109.0,9.0,25.0,549.0,44.0,1
2,1,0,3,58.0,1,43.0,3576.0,0.0,6715.0,49.0,0
3,1,0,3,33.0,0,0.0,1283.0,371.0,3329.0,193.0,0
4,0,0,3,16.0,0,303.0,70.0,151.0,565.0,2.0,1

In [71]:
from sklearn.preprocessing import MinMaxScaler

mnmx = MinMaxScaler()
for l in lst :
  train[l] = mnmx.fit_transform(train[[l]])

train.head()

,HomePlanet,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported
0,1,0,3,0.493671,0,0.000000,0.000000,0.000000,0.000000,0.000000,0
1,0,0,3,0.303797,0,0.007608,0.000302,0.001064,0.024500,0.001823,1
2,1,0,3,0.734177,1,0.003001,0.119948,0.000000,0.299670,0.002030,0
3,1,0,3,0.417722,0,0.000000,0.043035,0.015793,0.148563,0.007997,0
4,0,0,3,0.202532,0,0.021149,0.002348,0.006428,0.025214,0.000083,1

In [72]:
y = train['Transported']
x = train.drop('Transported' , axis = 1)

y.head()

0    0
1    1
2    0
3    0
4    1
Name: Transported, dtype: int64

In [74]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()

logreg.fit(x,y)

logreg.score(x,y)

0.763027723455654

In [75]:
from sklearn.tree import DecisionTreeClassifier

dectree = DecisionTreeClassifier()
dectree.fit(x,y)

dectree.score(x,y)

0.9375359484642816

In [78]:
from sklearn.ensemble import RandomForestClassifier
randomforest = RandomForestClassifier(n_estimators = 100)
randomforest.fit(x, y)

score = randomforest.score(x, y)
print(score)

0.9375359484642816

In [84]:
# test = test.drop('Cabin' , axis = 1)
pid = test['PassengerId']
# test = test.drop('PassengerId' , axis = 1)
# test = test.drop('Name' , axis = 1)

test['HomePlanet'].fillna('OtherPlanet' , inplace = True)
test['Destination'].fillna('OtherDestination' , inplace = True)
test['CryoSleep'].fillna(False , inplace = True)
test['VIP'].fillna(False , inplace = True)

lst = [ 'Age' , 'RoomService' , 'FoodCourt' , 'ShoppingMall' , 'Spa' , 'VRDeck']

for l in lst :
  test[l].fillna(test[l].mean() , inplace = True)

test['HomePlanet'] = label_encoder.fit_transform(test['HomePlanet'])
test['Destination'] = label_encoder.fit_transform(test['Destination'])
test['CryoSleep'] = label_encoder.fit_transform(test['CryoSleep'])
test['VIP'] = label_encoder.fit_transform(test['VIP'])
for l in lst :
  test[l] = mnmx.fit_transform(test[[l]])

test.head()

,HomePlanet,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
0,0,1,3,0.341772,0,0.000000,0.000000,0.00000,0.000000,0.000000
1,0,0,3,0.240506,0,0.000000,0.000356,0.00000,0.142260,0.000000
2,1,1,0,0.392405,0,0.000000,0.000000,0.00000,0.000000,0.000000
3,1,0,3,0.481013,0,0.000000,0.263206,0.00000,0.009121,0.026266
4,0,0,3,0.253165,0,0.000865,0.000000,0.07658,0.000000,0.000000

In [85]:
test.head()

,HomePlanet,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
0,0,1,3,0.341772,0,0.000000,0.000000,0.00000,0.000000,0.000000
1,0,0,3,0.240506,0,0.000000,0.000356,0.00000,0.142260,0.000000
2,1,1,0,0.392405,0,0.000000,0.000000,0.00000,0.000000,0.000000
3,1,0,3,0.481013,0,0.000000,0.263206,0.00000,0.009121,0.026266
4,0,0,3,0.253165,0,0.000865,0.000000,0.07658,0.000000,0.000000

In [86]:
pid

0       0013_01
1       0018_01
2       0019_01
3       0021_01
4       0023_01
         ...
4272    9266_02
4273    9269_01
4274    9271_01
4275    9273_01
4276    9277_01
Name: PassengerId, Length: 4277, dtype: object

In [124]:
pred = logreg.predict(test)

In [125]:
predicted = pd.DataFrame(pred)
passid = pd.DataFrame(pid)
predicted

finaldf = pd.concat([passid , predicted] , axis = 1)
finaldf = finaldf.replace(0 , False)
finaldf = finaldf.replace(1 , True)
finaldf.columns = ['PassengerId' , 'Transported']
finaldf.head()
finaldf.to_csv('submission.csv',index=False)
files.download('submission.csv')